ext {
    extName = 'Wolf.com'
    extClass = '.WolfFactory'
    extVersionCode = 11
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

android {
    testOptions {
        unitTests.returnDefaultValues = true
    }

    sourceSets {
        test {
            java.srcDirs = ['test']
            kotlin.srcDirs = ['test']
        }
    }
}

dependencies {
    testImplementation libs.bundles.common
    testImplementation libs.junit
}
